### ISSUE TITLE
講義選択時になんらかのフィードバックが欲しい

### ISSUE THREAD

**Issue by pentaCoxian** [RRRGR/ICUApp#10]
講義選択したあと時間割表示に戻るのが一番わかりやすい挙動かとは思うんだけど[前の実装](https://github.com/RRRGR/ICUApp/pull/8)が不安定すぎたからなんとかしたい。

**Comment by pentaCoxian** [comment]
一つやれるのはsaveが処理に時間かかってるのがある程度原因だろうから組鋳込みのDBに変更するときに実装するとか？

**Comment by RRRGR** [comment]
solved in 2160df9ebc5960d6552ad2d91cd2d9581fa224f5
